In [3]:
import numpy as np

In [95]:
def vander_monde(vector,N,increasing=False):
    if(increasing==False):
        y=np.array([(np.array(vector))**(N-i-1) for i in range(N)] ).T
        print(y)
    if(increasing==True):
        z=np.flip(np.array([(np.array(vector))**(N-i-1) for i in range(N)] ).T,axis=1)
        print(z)

In [99]:
vander_monde([1,2,5,8],3,False)

[[ 1  1  1]
 [ 4  2  1]
 [25  5  1]
 [64  8  1]]


In [100]:
vander_monde([1,2,5,6,9],4,True)

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   5  25 125]
 [  1   6  36 216]
 [  1   9  81 729]]


In [57]:
def moving_averages(l,k):
    i=0
    moving_average=[]
    while i < n - k + 1:
        current_window = l[i : i + k]
        current_average = sum(current_window) / k
        moving_average.append(current_average)
        i += 1
    print(moving_average)           

In [58]:
moving_averages([10,20,30,40,50,60,70,80,90,100],4)

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]


In [59]:
moving_averages([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667]
